const AppColors = {
  appThemeColor: '#FF7200',
  background: 'white',
  whiteTitle:'white',
  blackTitle:'black',
  blueColor:'blue',
  grayTitle:'gray',
  backgroundGray:'gray',
  dateBackground: '#F5791F',
  contentBackground: '#F5791F',
  shadowColor: "#000",
  checkoutCellBackground:'#CCCCCC',
  keyboardVoiding:'#349db',
  transparent: 'clear',
  datePickerBackgroundColor:'#FF7200',
  pickerHeaderStyleColor: '#EE7933',
  addTaskBackgroundColor: '#EEEEEE',
  healthViewBackgroundColor: '#F2F2F2',
  designationHealthBackgroundColor: '#FAFAFA',
  borderLightGrayColor: 'lightgray',
  projectItemBackgroundColor: '#535353',
  taskNameCardBackgroundColor: '#e6e8e8',
  dialogBackgroundColor: '#A6A6A6',
  blueAppThemeColor: '#123D5C',
  lightAppThemeColor: '#2B86C5',
  jobBackgroundColor: '#B9DAF0B2',
}
export default AppColors