export {default as Login} from './Login'
export {default as OTP} from './OTP'
export {default as Password} from './Password'
export {default as Dashboard} from './Dashboard'
export {default as Profile} from './Profile'
export {default as MyAttendance} from './MyAttendance'
export {default as CheckInConfirmation} from './CheckInConfirmation'
export {default as CheckOutConfirmation} from './CheckOutConfirmation'
export {default as AddTask} from './AddTask'
export {default as TaskList} from './TaskList'
export {default as ProjectList} from './ProjectList'
export {default as HealthFeedback} from './HealthFeedback'
export {default as TeamList} from './TeamList'
export {default as TaskSummary} from './TaskSummary'
export {default as ApplyLeave} from './ApplyLeave'
export {default as Splash} from './Splash'

export {default as Simple} from './Simple'
export {default as Home} from './Home'
export {default as DemoProceed} from './DemoProceed'
export {default as JobDetail} from './JobDetail'
export {default as Appointment} from './Appointment'
export {default as PostJob} from './PostJob'
export {default as AddEmployee} from './AddEmployee'
export {default as Screening} from './Screening'

export {default as AppColors} from './AppColors'

